name: .NET Desktop App CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore NuGet packages
      run: dotnet restore ./ShapeDungeon/ShapeDungeon.sln

    - name: Build the solution
      run: dotnet build ./ShapeDungeon/ShapeDungeon.sln --configuration Release

    - name: Run tests
      run: dotnet test ./ShapeDungeon.Tests/ShapeDungeon.Tests.csproj --configuration Release
